### ISSUE TITLE
Add CDN support

### ISSUE THREAD

**Issue by satyarohith** [satyarohith/shark#34]
Refer [DigitalOcean](https://developers.digitalocean.com/documentation/v2/#cdn-endpoints) and [do-wrapper](https://github.com/matt-major/do-wrapper/blob/master/docs/do-wrapper.md#cdnEndpointCreate) docs.

Add the following commands:
- [ ] `shark cdn:create`
- [ ] `shark cdn:delete`
- [ ] `shark cdn:list`
- [ ] `shark cdn:get`
- [ ] `shark cdn:purge`

Use oclif to bootstrap commands. 

Example:
 ```sh
oclif command cdn:create
```
And add the necessary tests. Thanks!

**Comment by lukebrewerton** [comment]
I'll take a look at this

**Comment by littlestar642** [comment]
Hey. I would like to work on this. Can you please assign it to me.

**Comment by littlestar642** [comment]
`cdnEndpointCreate(origin, ttl, [callback])`
For this api, do we need to get the `origin` parameter from the user using a prompt?
Also do I need to define it in `prompts/index.js`

**Comment by satyarohith** [comment]
Hey, thanks for the interest. I'm currently on a trip. Will get back to you
as soon as possible. :)

**Comment by satyarohith** [comment]
> For this api, do we need to get the `origin` parameter from the user using a prompt?

Yes. If the value is not passed via a flag then trigger a prompt. See [`domains/create.js`](https://github.com/satyarohith/shark/blob/29ab2f55f43483162c28baf731ea7bc20b176530/src/commands/domains/create.js#L14) for inspiration.

> Also do I need to define it in `prompts/index.js`

Creating a separate file for all prompts related to `cdn` would be better.

**Comment by littlestar642** [comment]
Hi. I completed making the create.js for cdn. I need some help with the tests. How to perform the tests? and what should be the assertion condition?

**Comment by satyarohith** [comment]
You need to mock the network requests and test the command. See [this](https://github.com/satyarohith/shark/blob/dev/test/commands/domains/create.test.js) to get an idea. And make a pull request with your code. It helps me guide you better.
