### ISSUE TITLE
Is it possible to use shark on commandline without user interaction?

### ISSUE THREAD

**Issue by computersrmyfriends** [satyarohith/shark#6]
**Can I use this in a bash script without waiting for the prompts?**

I want to use shark to create droplet through commandline without user interaction. Is this possible?

Thanks

**Comment by satyarohith** [comment]
For now, No! I made shark to be an Interactive tool but it’s true that it reduces productivity to wait for prompts. I’m thinking about how to solve this, would love your thoughts.
https://github.com/digitalocean/doctl will be helpful for your use case.
